name: Maven Build Pipeline

on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        
     # 2. Verify Java
      - name: Check Java Version
        run: java -

      # 3. Build with Maven
      - name: Build Project
        run: mvn clean package

      # 4. copy artifact to /opt/app
      - name: delever artifact
        run: sudo cp /target/*.jar /opt/
        
