name: My First Workflow

on: workflow_dispatch

jobs:
  stage1:
    runs-on: self-hosted
    steps:
      - name: Stage 1 Echo
        run: echo "Hello from Stage 1"

  stage2:
    runs-on: self-hosted
    needs: stage1
    steps:
      - name: Stage 2 Echo
        run: date

  stage3:
    runs-on: self-hosted
    needs: stage2
    steps:
      - name: Stage 3 Echo
        run: pwd
